"""
    StitchCredit API

    StitchCredit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ecreditapi.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from ecreditapi.model.code_description import CodeDescription
    from ecreditapi.model.contact_information import ContactInformation
    from ecreditapi.model.money import Money
    from ecreditapi.model.payment_history_year import PaymentHistoryYear
    from ecreditapi.model.trended_data_history import TrendedDataHistory
    globals()['CodeDescription'] = CodeDescription
    globals()['ContactInformation'] = ContactInformation
    globals()['Money'] = Money
    globals()['PaymentHistoryYear'] = PaymentHistoryYear
    globals()['TrendedDataHistory'] = TrendedDataHistory


class CreditReportAccount(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('provider',): {
            'EFX': "EFX",
            'TU': "TU",
            'EXP': "EXP",
            'UNKNOWN': "UNKNOWN",
        },
        ('account_status',): {
            'BANKRUPTCY_OR_WAGE_EARNER_PLAN': "BANKRUPTCY_OR_WAGE_EARNER_PLAN",
            'COLLECTION_OR_CHARGEOFF': "COLLECTION_OR_CHARGEOFF",
            'FORECLOSURE': "FORECLOSURE",
            'FORECLOSURE_OR_REPOSSESSION': "FORECLOSURE_OR_REPOSSESSION",
            'LATE_30_DAYS': "LATE_30_DAYS",
            'LATE_60_DAYS': "LATE_60_DAYS",
            'LATE_90_DAYS': "LATE_90_DAYS",
            'WAGE_EARNER_PLAN': "WAGE_EARNER_PLAN",
            'TOO_NEW_TO_RATE': "TOO_NEW_TO_RATE",
            'PAYS_AS_AGREED': "PAYS_AS_AGREED",
            'NOT_MORE_THAN_TWO_PAYMENTS_PAST_DUE': "NOT_MORE_THAN_TWO_PAYMENTS_PAST_DUE",
            'NOT_MORE_THAN_THREE_PAYMENTS_PAST_DUE': "NOT_MORE_THAN_THREE_PAYMENTS_PAST_DUE",
            'NOT_MORE_THAN_FOUR_PAYMENTS_PAST_DUE': "NOT_MORE_THAN_FOUR_PAYMENTS_PAST_DUE",
            'OVER_120_DAYS_PAST_DUE': "OVER_120_DAYS_PAST_DUE",
            'COLLECTION': "COLLECTION",
            'INCLUDED_IN_CHAPTER_13': "INCLUDED_IN_CHAPTER_13",
            'REPOSSESSION': "REPOSSESSION",
            'CHARGE_OFF': "CHARGE_OFF",
            'ZERO_BALANCE_AND_CURRENT_ACCOUNT': "ZERO_BALANCE_AND_CURRENT_ACCOUNT",
            'NO_RATE_REPORTED': "NO_RATE_REPORTED",
            'ACCOUNT_INACTIVE': "ACCOUNT_INACTIVE",
            'LOST_OR_STOLEN_CARD': "LOST_OR_STOLEN_CARD",
            'CONTACT_MEMBER_FOR_STATUS': "CONTACT_MEMBER_FOR_STATUS",
            'REFINANCED_OR_RENEWED': "REFINANCED_OR_RENEWED",
            'CONSUMER_DECEASED': "CONSUMER_DECEASED",
            'IN_FINANCIAL_COUNSELING': "IN_FINANCIAL_COUNSELING",
            'FORECLOSURE_PROCESS_STARTED': "FORECLOSURE_PROCESS_STARTED",
            'IN_WEP': "IN_WEP",
            'ADJUSTMENT_PENDING': "ADJUSTMENT_PENDING",
            'DISPUTE_RESOLUTION_PENDING': "DISPUTE_RESOLUTION_PENDING",
            'INCLUDED_IN_BANKRUPTCY': "INCLUDED_IN_BANKRUPTCY",
            'IN_BK': "IN_BK",
            'ASSIGNED_TO_US_DEPT_OF_ED': "ASSIGNED_TO_US_DEPT_OF_ED",
            'UNAVAILABLE': "UNAVAILABLE",
        },
        ('payment_responsibility',): {
            'INDIVIDUAL': "INDIVIDUAL",
            'JOINT_CONTRACTUAL_LIABILITY': "JOINT_CONTRACTUAL_LIABILITY",
            'SHARED': "SHARED",
            'UNDESIGNATED': "UNDESIGNATED",
        },
        ('account_type',): {
            'REVOLVING': "REVOLVING",
            'MORTGAGE': "MORTGAGE",
            'INSTALLMENT': "INSTALLMENT",
            'OTHER': "OTHER",
        },
        ('creditor_classification',): {
            'ADVERTISING': "ADVERTISING",
            'CLOTHING': "CLOTHING",
            'COLLECTION_SERVICES': "COLLECTION_SERVICES",
            'CONTRACTORS': "CONTRACTORS",
            'DEPARTMENT_AND_MAIL_ORDER': "DEPARTMENT_AND_MAIL_ORDER",
            'EMPLOYMENT': "EMPLOYMENT",
            'FARM_AND_GARDEN_SUPPLIES': "FARM_AND_GARDEN_SUPPLIES",
            'FINANCE': "FINANCE",
            'GROCERY': "GROCERY",
            'HOME_FURNISHING': "HOME_FURNISHING",
            'JEWELRY_AND_CAMERA': "JEWELRY_AND_CAMERA",
            'LUMBER_AND_HARDWARE': "LUMBER_AND_HARDWARE",
            'MEDICAL_AND_HEALTH': "MEDICAL_AND_HEALTH",
            'MISCELLANEOUS_AND_PUBLIC_RECORD': "MISCELLANEOUS_AND_PUBLIC_RECORD",
            'OIL_AND_NATIONAL_CREDIT_CARDS': "OIL_AND_NATIONAL_CREDIT_CARDS",
            'PERSONAL_SERVICES_NOT_MEDICAL': "PERSONAL_SERVICES_NOT_MEDICAL",
            'REAL_ESTATE_AND_PUBLIC_ACCOMMODATION': "REAL_ESTATE_AND_PUBLIC_ACCOMMODATION",
            'SPORTING_GOODS': "SPORTING_GOODS",
            'UTILITIES_AND_FUEL': "UTILITIES_AND_FUEL",
            'WHOLESALE': "WHOLESALE",
            'AUTOMOTIVE': "AUTOMOTIVE",
            'BANKING': "BANKING",
            'CABLE_OR_CELLULAR': "CABLE_OR_CELLULAR",
            'CHECK_GUARANTEE': "CHECK_GUARANTEE",
            'CREDIT_UNION': "CREDIT_UNION",
            'EDUCATIONAL': "EDUCATIONAL",
            'FINANCIAL': "FINANCIAL",
            'GOVERNMENT': "GOVERNMENT",
            'INSURANCE': "INSURANCE",
            'MEDICAL_OR_HEALTH_CARE': "MEDICAL_OR_HEALTH_CARE",
            'OIL_COMPANY': "OIL_COMPANY",
            'PERSONAL_SERVICES': "PERSONAL_SERVICES",
            'RENTAL_OR_LEASING': "RENTAL_OR_LEASING",
            'RETAIL': "RETAIL",
            'UTILITIES': "UTILITIES",
            'UNKNOWN': "UNKNOWN",
        },
        ('activity_designator',): {
            'CLOSED': "CLOSED",
            'DEFAULT': "DEFAULT",
            'FROZEN': "FROZEN",
            'LOST_OR_STOLEN': "LOST_OR_STOLEN",
            'OPEN': "OPEN",
            'PAID': "PAID",
            'PAID_AND_CLOSED': "PAID_AND_CLOSED",
            'REFINANCED': "REFINANCED",
            'TRANSFER_OR_SOLD': "TRANSFER_OR_SOLD",
            'TRANSFER_OR_SOLD_OR_PAID': "TRANSFER_OR_SOLD_OR_PAID",
            'TRANSFERRED': "TRANSFERRED",
            'UNKNOWN': "UNKNOWN",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'provider': (str,),  # noqa: E501
            'id': (str,),  # noqa: E501
            'account_open': (bool,),  # noqa: E501
            'account_name': (str,),  # noqa: E501
            'contact_information': (ContactInformation,),  # noqa: E501
            'account_number': (str,),  # noqa: E501
            'account_status': (str,),  # noqa: E501
            'payment_responsibility': (str,),  # noqa: E501
            'high_credit_amount': (Money,),  # noqa: E501
            'account_type': (str,),  # noqa: E501
            'credit_limit_amount': (Money,),  # noqa: E501
            'term_duration_months': (int,),  # noqa: E501
            'term_frequency': (str,),  # noqa: E501
            'date_opened': (datetime,),  # noqa: E501
            'balance_amount': (Money,),  # noqa: E501
            'reported_date': (datetime,),  # noqa: E501
            'past_due_amount': (Money,),  # noqa: E501
            'last_payment_date': (datetime,),  # noqa: E501
            'actual_payment': (Money,),  # noqa: E501
            'monthly_payment': (Money,),  # noqa: E501
            'last_activity_date': (datetime,),  # noqa: E501
            'major_delinquency_first_reported_date': (datetime,),  # noqa: E501
            'months_reviewed': (int,),  # noqa: E501
            'creditor_classification': (str,),  # noqa: E501
            'activity_designator': (str,),  # noqa: E501
            'charge_off_amount': (Money,),  # noqa: E501
            'deferred_payment_start_date': (datetime,),  # noqa: E501
            'balloon_payment_amount': (Money,),  # noqa: E501
            'balloon_payment_date': (datetime,),  # noqa: E501
            'date_closed': (datetime,),  # noqa: E501
            'loan_type': (CodeDescription,),  # noqa: E501
            'first_delinquency_date': (datetime,),  # noqa: E501
            'comments': ([CodeDescription],),  # noqa: E501
            'payment_history': ([PaymentHistoryYear],),  # noqa: E501
            'trended_data_history': (TrendedDataHistory,),  # noqa: E501
            'is_negative': (bool,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'provider': 'provider',  # noqa: E501
        'id': 'id',  # noqa: E501
        'account_open': 'accountOpen',  # noqa: E501
        'account_name': 'accountName',  # noqa: E501
        'contact_information': 'contactInformation',  # noqa: E501
        'account_number': 'accountNumber',  # noqa: E501
        'account_status': 'accountStatus',  # noqa: E501
        'payment_responsibility': 'paymentResponsibility',  # noqa: E501
        'high_credit_amount': 'highCreditAmount',  # noqa: E501
        'account_type': 'accountType',  # noqa: E501
        'credit_limit_amount': 'creditLimitAmount',  # noqa: E501
        'term_duration_months': 'termDurationMonths',  # noqa: E501
        'term_frequency': 'termFrequency',  # noqa: E501
        'date_opened': 'dateOpened',  # noqa: E501
        'balance_amount': 'balanceAmount',  # noqa: E501
        'reported_date': 'reportedDate',  # noqa: E501
        'past_due_amount': 'pastDueAmount',  # noqa: E501
        'last_payment_date': 'lastPaymentDate',  # noqa: E501
        'actual_payment': 'actualPayment',  # noqa: E501
        'monthly_payment': 'monthlyPayment',  # noqa: E501
        'last_activity_date': 'lastActivityDate',  # noqa: E501
        'major_delinquency_first_reported_date': 'majorDelinquencyFirstReportedDate',  # noqa: E501
        'months_reviewed': 'monthsReviewed',  # noqa: E501
        'creditor_classification': 'creditorClassification',  # noqa: E501
        'activity_designator': 'activityDesignator',  # noqa: E501
        'charge_off_amount': 'chargeOffAmount',  # noqa: E501
        'deferred_payment_start_date': 'deferredPaymentStartDate',  # noqa: E501
        'balloon_payment_amount': 'balloonPaymentAmount',  # noqa: E501
        'balloon_payment_date': 'balloonPaymentDate',  # noqa: E501
        'date_closed': 'dateClosed',  # noqa: E501
        'loan_type': 'loanType',  # noqa: E501
        'first_delinquency_date': 'firstDelinquencyDate',  # noqa: E501
        'comments': 'comments',  # noqa: E501
        'payment_history': 'paymentHistory',  # noqa: E501
        'trended_data_history': 'trendedDataHistory',  # noqa: E501
        'is_negative': 'isNegative',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """CreditReportAccount - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            provider (str): [optional]  # noqa: E501
            id (str): [optional]  # noqa: E501
            account_open (bool): [optional]  # noqa: E501
            account_name (str): [optional]  # noqa: E501
            contact_information (ContactInformation): [optional]  # noqa: E501
            account_number (str): [optional]  # noqa: E501
            account_status (str): [optional]  # noqa: E501
            payment_responsibility (str): [optional]  # noqa: E501
            high_credit_amount (Money): [optional]  # noqa: E501
            account_type (str): [optional]  # noqa: E501
            credit_limit_amount (Money): [optional]  # noqa: E501
            term_duration_months (int): [optional]  # noqa: E501
            term_frequency (str): [optional]  # noqa: E501
            date_opened (datetime): [optional]  # noqa: E501
            balance_amount (Money): [optional]  # noqa: E501
            reported_date (datetime): [optional]  # noqa: E501
            past_due_amount (Money): [optional]  # noqa: E501
            last_payment_date (datetime): [optional]  # noqa: E501
            actual_payment (Money): [optional]  # noqa: E501
            monthly_payment (Money): [optional]  # noqa: E501
            last_activity_date (datetime): [optional]  # noqa: E501
            major_delinquency_first_reported_date (datetime): [optional]  # noqa: E501
            months_reviewed (int): [optional]  # noqa: E501
            creditor_classification (str): [optional]  # noqa: E501
            activity_designator (str): [optional]  # noqa: E501
            charge_off_amount (Money): [optional]  # noqa: E501
            deferred_payment_start_date (datetime): [optional]  # noqa: E501
            balloon_payment_amount (Money): [optional]  # noqa: E501
            balloon_payment_date (datetime): [optional]  # noqa: E501
            date_closed (datetime): [optional]  # noqa: E501
            loan_type (CodeDescription): [optional]  # noqa: E501
            first_delinquency_date (datetime): [optional]  # noqa: E501
            comments ([CodeDescription]): [optional]  # noqa: E501
            payment_history ([PaymentHistoryYear]): [optional]  # noqa: E501
            trended_data_history (TrendedDataHistory): [optional]  # noqa: E501
            is_negative (bool): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
