# coding: utf-8

"""
    StitchCredit API

    StitchCredit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sc-direct-api.configuration import Configuration


class ApplicationContextClassLoaderParentUnnamedModuleDescriptor(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'open': 'bool',
        'automatic': 'bool'
    }

    attribute_map = {
        'open': 'open',
        'automatic': 'automatic'
    }

    def __init__(self, open=None, automatic=None, local_vars_configuration=None):  # noqa: E501
        """ApplicationContextClassLoaderParentUnnamedModuleDescriptor - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._open = None
        self._automatic = None
        self.discriminator = None

        if open is not None:
            self.open = open
        if automatic is not None:
            self.automatic = automatic

    @property
    def open(self):
        """Gets the open of this ApplicationContextClassLoaderParentUnnamedModuleDescriptor.  # noqa: E501


        :return: The open of this ApplicationContextClassLoaderParentUnnamedModuleDescriptor.  # noqa: E501
        :rtype: bool
        """
        return self._open

    @open.setter
    def open(self, open):
        """Sets the open of this ApplicationContextClassLoaderParentUnnamedModuleDescriptor.


        :param open: The open of this ApplicationContextClassLoaderParentUnnamedModuleDescriptor.  # noqa: E501
        :type: bool
        """

        self._open = open

    @property
    def automatic(self):
        """Gets the automatic of this ApplicationContextClassLoaderParentUnnamedModuleDescriptor.  # noqa: E501


        :return: The automatic of this ApplicationContextClassLoaderParentUnnamedModuleDescriptor.  # noqa: E501
        :rtype: bool
        """
        return self._automatic

    @automatic.setter
    def automatic(self, automatic):
        """Sets the automatic of this ApplicationContextClassLoaderParentUnnamedModuleDescriptor.


        :param automatic: The automatic of this ApplicationContextClassLoaderParentUnnamedModuleDescriptor.  # noqa: E501
        :type: bool
        """

        self._automatic = automatic

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplicationContextClassLoaderParentUnnamedModuleDescriptor):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApplicationContextClassLoaderParentUnnamedModuleDescriptor):
            return True

        return self.to_dict() != other.to_dict()
