# coding: utf-8

"""
    StitchCredit API

    StitchCredit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sc-direct-api.configuration import Configuration


class ChangeEmailReqDTO(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'email': 'str',
        'recovery_answer': 'str',
        'token': 'str'
    }

    attribute_map = {
        'email': 'email',
        'recovery_answer': 'recoveryAnswer',
        'token': 'token'
    }

    def __init__(self, email=None, recovery_answer=None, token=None, local_vars_configuration=None):  # noqa: E501
        """ChangeEmailReqDTO - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._email = None
        self._recovery_answer = None
        self._token = None
        self.discriminator = None

        self.email = email
        self.recovery_answer = recovery_answer
        self.token = token

    @property
    def email(self):
        """Gets the email of this ChangeEmailReqDTO.  # noqa: E501


        :return: The email of this ChangeEmailReqDTO.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ChangeEmailReqDTO.


        :param email: The email of this ChangeEmailReqDTO.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and email is None:  # noqa: E501
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def recovery_answer(self):
        """Gets the recovery_answer of this ChangeEmailReqDTO.  # noqa: E501


        :return: The recovery_answer of this ChangeEmailReqDTO.  # noqa: E501
        :rtype: str
        """
        return self._recovery_answer

    @recovery_answer.setter
    def recovery_answer(self, recovery_answer):
        """Sets the recovery_answer of this ChangeEmailReqDTO.


        :param recovery_answer: The recovery_answer of this ChangeEmailReqDTO.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and recovery_answer is None:  # noqa: E501
            raise ValueError("Invalid value for `recovery_answer`, must not be `None`")  # noqa: E501

        self._recovery_answer = recovery_answer

    @property
    def token(self):
        """Gets the token of this ChangeEmailReqDTO.  # noqa: E501


        :return: The token of this ChangeEmailReqDTO.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this ChangeEmailReqDTO.


        :param token: The token of this ChangeEmailReqDTO.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and token is None:  # noqa: E501
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChangeEmailReqDTO):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ChangeEmailReqDTO):
            return True

        return self.to_dict() != other.to_dict()
