# coding: utf-8

"""
    StitchCredit API

    StitchCredit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sc-direct-api.configuration import Configuration


class ContactInformation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'contact_name': 'str',
        'address': 'InternationalAddress',
        'phone': 'InternationalPhone'
    }

    attribute_map = {
        'contact_name': 'contactName',
        'address': 'address',
        'phone': 'phone'
    }

    def __init__(self, contact_name=None, address=None, phone=None, local_vars_configuration=None):  # noqa: E501
        """ContactInformation - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._contact_name = None
        self._address = None
        self._phone = None
        self.discriminator = None

        if contact_name is not None:
            self.contact_name = contact_name
        if address is not None:
            self.address = address
        if phone is not None:
            self.phone = phone

    @property
    def contact_name(self):
        """Gets the contact_name of this ContactInformation.  # noqa: E501


        :return: The contact_name of this ContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._contact_name

    @contact_name.setter
    def contact_name(self, contact_name):
        """Sets the contact_name of this ContactInformation.


        :param contact_name: The contact_name of this ContactInformation.  # noqa: E501
        :type: str
        """

        self._contact_name = contact_name

    @property
    def address(self):
        """Gets the address of this ContactInformation.  # noqa: E501


        :return: The address of this ContactInformation.  # noqa: E501
        :rtype: InternationalAddress
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ContactInformation.


        :param address: The address of this ContactInformation.  # noqa: E501
        :type: InternationalAddress
        """

        self._address = address

    @property
    def phone(self):
        """Gets the phone of this ContactInformation.  # noqa: E501


        :return: The phone of this ContactInformation.  # noqa: E501
        :rtype: InternationalPhone
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this ContactInformation.


        :param phone: The phone of this ContactInformation.  # noqa: E501
        :type: InternationalPhone
        """

        self._phone = phone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactInformation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContactInformation):
            return True

        return self.to_dict() != other.to_dict()
