# coding: utf-8

"""
    StitchCredit API

    StitchCredit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sc-direct-api.configuration import Configuration


class Inquiry(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'provider': 'str',
        'id': 'str',
        'type': 'str',
        'prefix': 'object',
        'reported_date': 'datetime',
        'contact_information': 'object'
    }

    attribute_map = {
        'provider': 'provider',
        'id': 'id',
        'type': 'type',
        'prefix': 'prefix',
        'reported_date': 'reportedDate',
        'contact_information': 'contactInformation'
    }

    def __init__(self, provider=None, id=None, type=None, prefix=None, reported_date=None, contact_information=None, local_vars_configuration=None):  # noqa: E501
        """Inquiry - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._provider = None
        self._id = None
        self._type = None
        self._prefix = None
        self._reported_date = None
        self._contact_information = None
        self.discriminator = None

        if provider is not None:
            self.provider = provider
        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if prefix is not None:
            self.prefix = prefix
        if reported_date is not None:
            self.reported_date = reported_date
        if contact_information is not None:
            self.contact_information = contact_information

    @property
    def provider(self):
        """Gets the provider of this Inquiry.  # noqa: E501


        :return: The provider of this Inquiry.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this Inquiry.


        :param provider: The provider of this Inquiry.  # noqa: E501
        :type: str
        """
        allowed_values = ["EFX", "TU", "EXP", "UNKNOWN"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and provider not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"  # noqa: E501
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def id(self):
        """Gets the id of this Inquiry.  # noqa: E501


        :return: The id of this Inquiry.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Inquiry.


        :param id: The id of this Inquiry.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this Inquiry.  # noqa: E501


        :return: The type of this Inquiry.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Inquiry.


        :param type: The type of this Inquiry.  # noqa: E501
        :type: str
        """
        allowed_values = ["HARD", "SOFT", "OTHER"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def prefix(self):
        """Gets the prefix of this Inquiry.  # noqa: E501


        :return: The prefix of this Inquiry.  # noqa: E501
        :rtype: object
        """
        return self._prefix

    @prefix.setter
    def prefix(self, prefix):
        """Sets the prefix of this Inquiry.


        :param prefix: The prefix of this Inquiry.  # noqa: E501
        :type: object
        """

        self._prefix = prefix

    @property
    def reported_date(self):
        """Gets the reported_date of this Inquiry.  # noqa: E501


        :return: The reported_date of this Inquiry.  # noqa: E501
        :rtype: datetime
        """
        return self._reported_date

    @reported_date.setter
    def reported_date(self, reported_date):
        """Sets the reported_date of this Inquiry.


        :param reported_date: The reported_date of this Inquiry.  # noqa: E501
        :type: datetime
        """

        self._reported_date = reported_date

    @property
    def contact_information(self):
        """Gets the contact_information of this Inquiry.  # noqa: E501


        :return: The contact_information of this Inquiry.  # noqa: E501
        :rtype: object
        """
        return self._contact_information

    @contact_information.setter
    def contact_information(self, contact_information):
        """Sets the contact_information of this Inquiry.


        :param contact_information: The contact_information of this Inquiry.  # noqa: E501
        :type: object
        """

        self._contact_information = contact_information

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Inquiry):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Inquiry):
            return True

        return self.to_dict() != other.to_dict()
