# coding: utf-8

"""
    StitchCredit API

    StitchCredit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sc-direct-api.configuration import Configuration


class PersonName(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'last_name': 'str',
        'first_name': 'str',
        'middle_name': 'str',
        'suffix': 'str'
    }

    attribute_map = {
        'last_name': 'lastName',
        'first_name': 'firstName',
        'middle_name': 'middleName',
        'suffix': 'suffix'
    }

    def __init__(self, last_name=None, first_name=None, middle_name=None, suffix=None, local_vars_configuration=None):  # noqa: E501
        """PersonName - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._last_name = None
        self._first_name = None
        self._middle_name = None
        self._suffix = None
        self.discriminator = None

        if last_name is not None:
            self.last_name = last_name
        if first_name is not None:
            self.first_name = first_name
        if middle_name is not None:
            self.middle_name = middle_name
        if suffix is not None:
            self.suffix = suffix

    @property
    def last_name(self):
        """Gets the last_name of this PersonName.  # noqa: E501


        :return: The last_name of this PersonName.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this PersonName.


        :param last_name: The last_name of this PersonName.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def first_name(self):
        """Gets the first_name of this PersonName.  # noqa: E501


        :return: The first_name of this PersonName.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this PersonName.


        :param first_name: The first_name of this PersonName.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def middle_name(self):
        """Gets the middle_name of this PersonName.  # noqa: E501


        :return: The middle_name of this PersonName.  # noqa: E501
        :rtype: str
        """
        return self._middle_name

    @middle_name.setter
    def middle_name(self, middle_name):
        """Sets the middle_name of this PersonName.


        :param middle_name: The middle_name of this PersonName.  # noqa: E501
        :type: str
        """

        self._middle_name = middle_name

    @property
    def suffix(self):
        """Gets the suffix of this PersonName.  # noqa: E501


        :return: The suffix of this PersonName.  # noqa: E501
        :rtype: str
        """
        return self._suffix

    @suffix.setter
    def suffix(self, suffix):
        """Sets the suffix of this PersonName.


        :param suffix: The suffix of this PersonName.  # noqa: E501
        :type: str
        """

        self._suffix = suffix

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PersonName):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PersonName):
            return True

        return self.to_dict() != other.to_dict()
