# coding: utf-8

"""
    StitchCredit API

    StitchCredit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sc-direct-api.configuration import Configuration


class TrendedDataHistory(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'trended_data_list': 'list[TrendedData]'
    }

    attribute_map = {
        'name': 'name',
        'trended_data_list': 'trendedDataList'
    }

    def __init__(self, name=None, trended_data_list=None, local_vars_configuration=None):  # noqa: E501
        """TrendedDataHistory - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._trended_data_list = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if trended_data_list is not None:
            self.trended_data_list = trended_data_list

    @property
    def name(self):
        """Gets the name of this TrendedDataHistory.  # noqa: E501


        :return: The name of this TrendedDataHistory.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TrendedDataHistory.


        :param name: The name of this TrendedDataHistory.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def trended_data_list(self):
        """Gets the trended_data_list of this TrendedDataHistory.  # noqa: E501


        :return: The trended_data_list of this TrendedDataHistory.  # noqa: E501
        :rtype: list[TrendedData]
        """
        return self._trended_data_list

    @trended_data_list.setter
    def trended_data_list(self, trended_data_list):
        """Sets the trended_data_list of this TrendedDataHistory.


        :param trended_data_list: The trended_data_list of this TrendedDataHistory.  # noqa: E501
        :type: list[TrendedData]
        """

        self._trended_data_list = trended_data_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrendedDataHistory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrendedDataHistory):
            return True

        return self.to_dict() != other.to_dict()
