# coding: utf-8

"""
    StitchCredit API

    StitchCredit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ecreditapi.configuration import Configuration


class CreditReport(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'provider_views': 'list[CreditReportProviderView]',
        'id': 'str',
        'report_type': 'str',
        'generated_date': 'int'
    }

    attribute_map = {
        'provider_views': 'providerViews',
        'id': 'id',
        'report_type': 'reportType',
        'generated_date': 'generatedDate'
    }

    def __init__(self, provider_views=None, id=None, report_type=None, generated_date=None, local_vars_configuration=None):  # noqa: E501
        """CreditReport - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._provider_views = None
        self._id = None
        self._report_type = None
        self._generated_date = None
        self.discriminator = None

        if provider_views is not None:
            self.provider_views = provider_views
        if id is not None:
            self.id = id
        if report_type is not None:
            self.report_type = report_type
        if generated_date is not None:
            self.generated_date = generated_date

    @property
    def provider_views(self):
        """Gets the provider_views of this CreditReport.  # noqa: E501


        :return: The provider_views of this CreditReport.  # noqa: E501
        :rtype: list[CreditReportProviderView]
        """
        return self._provider_views

    @provider_views.setter
    def provider_views(self, provider_views):
        """Sets the provider_views of this CreditReport.


        :param provider_views: The provider_views of this CreditReport.  # noqa: E501
        :type: list[CreditReportProviderView]
        """

        self._provider_views = provider_views

    @property
    def id(self):
        """Gets the id of this CreditReport.  # noqa: E501


        :return: The id of this CreditReport.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CreditReport.


        :param id: The id of this CreditReport.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def report_type(self):
        """Gets the report_type of this CreditReport.  # noqa: E501


        :return: The report_type of this CreditReport.  # noqa: E501
        :rtype: str
        """
        return self._report_type

    @report_type.setter
    def report_type(self, report_type):
        """Sets the report_type of this CreditReport.


        :param report_type: The report_type of this CreditReport.  # noqa: E501
        :type: str
        """
        allowed_values = ["US_EFX", "US_3B"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and report_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `report_type` ({0}), must be one of {1}"  # noqa: E501
                .format(report_type, allowed_values)
            )

        self._report_type = report_type

    @property
    def generated_date(self):
        """Gets the generated_date of this CreditReport.  # noqa: E501


        :return: The generated_date of this CreditReport.  # noqa: E501
        :rtype: int
        """
        return self._generated_date

    @generated_date.setter
    def generated_date(self, generated_date):
        """Sets the generated_date of this CreditReport.


        :param generated_date: The generated_date of this CreditReport.  # noqa: E501
        :type: int
        """

        self._generated_date = generated_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreditReport):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreditReport):
            return True

        return self.to_dict() != other.to_dict()
