# coding: utf-8

"""
    StitchCredit API

    StitchCredit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ecreditapi.configuration import Configuration


class CreditScoreReason(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'code': 'str',
        'description': 'str',
        'credit_score_factor_effect': 'str'
    }

    attribute_map = {
        'code': 'code',
        'description': 'description',
        'credit_score_factor_effect': 'creditScoreFactorEffect'
    }

    def __init__(self, code=None, description=None, credit_score_factor_effect=None, local_vars_configuration=None):  # noqa: E501
        """CreditScoreReason - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._code = None
        self._description = None
        self._credit_score_factor_effect = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if description is not None:
            self.description = description
        if credit_score_factor_effect is not None:
            self.credit_score_factor_effect = credit_score_factor_effect

    @property
    def code(self):
        """Gets the code of this CreditScoreReason.  # noqa: E501


        :return: The code of this CreditScoreReason.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this CreditScoreReason.


        :param code: The code of this CreditScoreReason.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def description(self):
        """Gets the description of this CreditScoreReason.  # noqa: E501


        :return: The description of this CreditScoreReason.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreditScoreReason.


        :param description: The description of this CreditScoreReason.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def credit_score_factor_effect(self):
        """Gets the credit_score_factor_effect of this CreditScoreReason.  # noqa: E501


        :return: The credit_score_factor_effect of this CreditScoreReason.  # noqa: E501
        :rtype: str
        """
        return self._credit_score_factor_effect

    @credit_score_factor_effect.setter
    def credit_score_factor_effect(self, credit_score_factor_effect):
        """Sets the credit_score_factor_effect of this CreditScoreReason.


        :param credit_score_factor_effect: The credit_score_factor_effect of this CreditScoreReason.  # noqa: E501
        :type: str
        """
        allowed_values = ["HELPING", "HURTING", "NEUTRAL"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and credit_score_factor_effect not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `credit_score_factor_effect` ({0}), must be one of {1}"  # noqa: E501
                .format(credit_score_factor_effect, allowed_values)
            )

        self._credit_score_factor_effect = credit_score_factor_effect

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreditScoreReason):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreditScoreReason):
            return True

        return self.to_dict() != other.to_dict()
